### model test용 세트

In [14]:
import numpy as np

with open('check_datalist.txt', 'w+') as w:
    for i in range(1,31):
        f=f'test_subset_rev0718_{i}.npz'
        data=np.load(f, allow_pickle=True)
        for j in data['tags'][:50].tolist():
            print(j)
            w.write(j+'\n')
    #check_data.append(data['tags'][:50].tolist())
w.close()

subset1|mol_197
subset1|mol_283
subset1|mol_36
subset1|mol_86
subset1|mol_207
subset1|mol_486
subset1|mol_735
subset1|mol_2124
subset1|mol_1905
subset1|mol_1273
subset1|mol_2264
subset1|mol_1095
subset1|mol_1335
subset1|mol_877
subset1|mol_384
subset1|mol_971
subset1|mol_2346
subset1|mol_300
subset1|mol_2380
subset1|mol_2338
subset1|mol_2297
subset1|mol_1707
subset1|mol_148
subset1|mol_314
subset1|mol_2208
subset1|mol_994
subset1|mol_1509
subset1|mol_879
subset1|mol_2151
subset1|mol_2006
subset1|mol_2113
subset1|mol_1465
subset1|mol_1579
subset1|mol_1135
subset1|mol_284
subset1|mol_72
subset1|mol_1952
subset1|mol_952
subset1|mol_1447
subset1|mol_689
subset1|mol_809
subset1|mol_1384
subset1|mol_1983
subset1|mol_940
subset1|mol_2011
subset1|mol_1639
subset1|mol_579
subset1|mol_517
subset1|mol_1803
subset1|mol_2408
subset2|mol_197
subset2|mol_283
subset2|mol_36
subset2|mol_86
subset2|mol_207
subset2|mol_486
subset2|mol_735
subset2|mol_2124
subset2|mol_1905
subset2|mol_1273
subset2|mol_109

In [13]:
import numpy as np

f='/home/kathy531/Caesar-lig/data/new_npz0718/test_subset_rev0718_1.npz'

data=np.load(f, allow_pickle=True)

#print(list(data.keys()))

#print(len(data['tags']))
#print(data['features'])
'''
print(list(data['tags']))
count=0
for i in list(data['tags']):
    if i=='subset1|mol_36':
        print(count)
    count+=1

'''
for i in list(data['features'][2].keys()):
    print(i)
    print(data['features'][2][i])
    print(data['features'][2][i].shape)
    print()
    

bond_idx
[[ 0  1]
 [ 1  2]
 [ 2  3]
 [ 3  4]
 [ 4  5]
 [ 5  6]
 [ 6  7]
 [ 7  8]
 [ 6  9]
 [ 9 10]
 [10 11]
 [ 5 12]
 [12 13]
 [13 14]
 [14 15]
 [15 16]
 [16 17]
 [15 18]
 [18 19]
 [19 20]
 [18 21]
 [21 22]
 [22 23]
 [13 24]
 [24 25]
 [25 26]
 [25 27]
 [25 28]
 [28 29]
 [28 30]
 [ 9  2]
 [21 12]
 [30  4]]
(33, 2)

bond_info
[[1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [1 0 0 0 0]]
(33, 5)

elems
[[1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0

In [2]:
import numpy as np
count=0
for i in range(1,31):
    pathway = f'/home/kathy531/Caesar-lig/data/new_npz0718/test_subset_rev0718_{i}.npz'
    dataopen = np.load(pathway, allow_pickle=True)
    
    count+= len(list(dataopen['tags']))
    print(len(list(dataopen['tags'])))
print(count)

2447
2451
2483
2475
2466
2470
2472
2452
2429
2225
2308
2349
2257
2254
1537
1936
2064
2389
2339
2043
1833
1454
1171
1797
995
391
362
399
420
141
54809
