In [1]:
import torch

/usr/local/lib/python3.8/dist-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
# 예제 데이터 생성 (len(Gs), nfull, max(njs))
len_Gs = 5
nfull = 10
max_njs = 7
target_tensor = torch.randn(len_Gs, nfull, 1)  # [len(Gs), nfull, 1] 텐서

# mask 생성 예제 (len(Gs), nfull, max(njs))
mask = torch.zeros((len_Gs, nfull, max_njs))
mask[:, :5, :5] = 1  # 예시로, 첫 5개의 노드를 활성화
print(mask)
# mask를 [len(Gs), nfull, 1] 형태로 변환
reduced_mask = mask[:, :, 0].unsqueeze(-1)
print(reduced_mask)
# 마스킹 적용
masked_tensor = target_tensor * reduced_mask

#print(masked_tensor)

tensor([[[1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0.],
         [1., 1., 1., 1., 1., 0., 0.],
         [0., 0., 0.,

In [12]:
# 예제 데이터 생성 (len(Gs), nfull, max(njs))
len_Gs = 5
nfull = 10
max_njs = 7
target_tensor = torch.randn(len_Gs, nfull, 1)  # [len(Gs), nfull, 1] 텐서
p1 = torch.ones(1)
#print(p1.shape)
# mask 생성 예제 (len(Gs), nfull, max(njs))
mask = torch.zeros((len_Gs, nfull, max_njs))
mask[:, :5, :5] = 1  # 예시로, 첫 5개의 노드를 활성화
#print(mask.shape)
#print(mask[0])
b=mask.shape[0]
i=mask.shape[1]
j=mask.shape[2]
reshapeT=mask.view(b,i*j,1)
print(reshapeT[0])
# mask를 [len(Gs), nfull, 1] 형태로 변환
reduced_mask = mask[:, :, 0].unsqueeze(-1)
#print(reduced_mask[0])
# 활성화된 노드의 개수 계산
active_nodes_count = reduced_mask.sum(dim=1).int()  # [len(Gs), 1] 텐서

# 활성화된 노드의 target_tensor 값만 선택
active_target_values = target_tensor[reduced_mask.bool()].view(-1, 1)
active_nodes_per_graph = (mask.sum(dim=2) > 0).sum(dim=1)
#print(active_nodes_per_graph)
'''
# 활성화된 노드의 개수 및 값 출력
for i in range(len_Gs):
    print(f"Graph {i+1}: Active nodes = {active_nodes_count[i].item()}")
    print(f"Target values: {active_target_values[:active_nodes_count[i].item()].tolist()}")
    active_target_values = active_target_values[active_nodes_count[i].item():]  # 다음 그래프의 값으로 이동'''

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])


'\n# 활성화된 노드의 개수 및 값 출력\nfor i in range(len_Gs):\n    print(f"Graph {i+1}: Active nodes = {active_nodes_count[i].item()}")\n    print(f"Target values: {active_target_values[:active_nodes_count[i].item()].tolist()}")\n    active_target_values = active_target_values[active_nodes_count[i].item():]  # 다음 그래프의 값으로 이동'

### 활성화된 노드 개수가 몇 개인지 파악해서 이걸로 노말라이즈하면 되지 않을까?

In [35]:
# Define the tensors
tensor1 = torch.randint(0,2,(3, 3, 1))  # Shape [5, 70, 1]
tensor2 = torch.randint(0,10,(3, 2))  # Shape [5, 70, 4]

# Perform element-wise multiplication with broadcasting
result = tensor1 * tensor2  # Resulting shape will be [5, 70, 4]

print(tensor1.sum())
# Verify the shape of the result#
print(tensor1)
print(tensor2)
print(result)  # Output: torch.Size([5, 70, 4])

tensor(5)
tensor([[[0],
         [1],
         [0]],

        [[1],
         [0],
         [0]],

        [[1],
         [1],
         [1]]])
tensor([[5, 6],
        [4, 0],
        [7, 3]])
tensor([[[0, 0],
         [4, 0],
         [0, 0]],

        [[5, 6],
         [0, 0],
         [0, 0]],

        [[5, 6],
         [4, 0],
         [7, 3]]])


In [21]:
print(torch.sum(result,dim=1))

tensor([[14, 10,  5,  4],
        [ 6, 17, 21, 13],
        [10,  8, 15, 16],
        [23, 21, 16, 15],
        [ 4,  6,  8,  3]])


In [36]:
tensor1 = torch.randint(0,2,(3, 3, 5))
tem=tensor1.view(3,3,1)
print(tem)

RuntimeError: shape '[3, 3, 1]' is invalid for input of size 45

In [39]:
tensor1 = torch.randint(0,2,(5, 5, 1))
print(tensor1)
print(tensor1.sum())

tensor([[[1],
         [0],
         [0],
         [1],
         [1]],

        [[1],
         [1],
         [1],
         [1],
         [0]],

        [[0],
         [0],
         [1],
         [1],
         [1]],

        [[1],
         [1],
         [0],
         [0],
         [0]],

        [[0],
         [1],
         [0],
         [0],
         [0]]])
tensor(13)


In [45]:
tensor1 = torch.randint(0,2,(5, 5, 5))
per_entropy_weight = torch.ones(1)
weight = torch.einsum('bij,k->bik', tensor1, per_entropy_weight)
print(weight.sum())
print(tensor1.sum())

print(weight)
print(tensor1)

tensor(64.)
tensor(64)
tensor([[[2.],
         [0.],
         [3.],
         [2.],
         [3.]],

        [[3.],
         [2.],
         [2.],
         [3.],
         [3.]],

        [[3.],
         [3.],
         [4.],
         [2.],
         [2.]],

        [[3.],
         [3.],
         [0.],
         [3.],
         [2.]],

        [[4.],
         [4.],
         [2.],
         [2.],
         [4.]]])
tensor([[[0, 1, 0, 0, 1],
         [0, 0, 0, 0, 0],
         [1, 0, 1, 0, 1],
         [1, 0, 0, 0, 1],
         [0, 1, 1, 1, 0]],

        [[1, 1, 0, 1, 0],
         [0, 0, 1, 0, 1],
         [0, 0, 1, 0, 1],
         [1, 1, 0, 0, 1],
         [1, 1, 0, 1, 0]],

        [[1, 0, 1, 1, 0],
         [0, 1, 0, 1, 1],
         [1, 1, 1, 0, 1],
         [1, 0, 0, 1, 0],
         [0, 0, 0, 1, 1]],

        [[1, 1, 0, 0, 1],
         [0, 1, 1, 0, 1],
         [0, 0, 0, 0, 0],
         [1, 0, 0, 1, 1],
         [0, 0, 0, 1, 1]],

        [[0, 1, 1, 1, 1],
         [1, 1, 1, 1, 0],
         [0,